import type { Config } from "tailwindcss";

const withOpacity = (variableName: string): any => {
  return ({ opacityValue }: { opacityValue?: string }) => {
    if (opacityValue !== undefined) {
      return `rgba(var(${variableName}-rgb), ${opacityValue})`;
    }
    return `var(${variableName})`;
  };
};

const config: Config = {
  content: [
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./templates/**/*.template.html",
    "./index.html",
  ],
  safelist: [
    "text-left",
    "text-center",
    "text-right",
    {
      pattern:
        /^(bg|text|border)-indicator-(unpaid|paid|submitted|success|error|draft|cancelled|gray|orange|green|red|yellow|blue|indigo|pink|purple|teal)-(bg|text|border)$/,
    },
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        black: "#1e293b",
        gray: {
          25: "#fbfbfb",
          50: "#f8f8f8",
          100: "#f3f3f3",
          200: "#ededed",
          300: "#e2e2e2",
          400: "#c7c7c7",
          500: "#999999",
          600: "#7c7c7c",
          700: "#525252",
          800: "#383838",
          850: "#282828",
          875: "#212121",
          890: "#1c1c1c",
          900: "#171717",
        },
        red: {
          50: "#fff7f7",
          100: "#fff0f0",
          200: "#fcd7d7",
          300: "#f9c6c6",
          400: "#eb9091",
          500: "#e03636",
          600: "#cc2929",
          700: "#b52a2a",
          800: "#941f1f",
          900: "#6b1515",
        },
        orange: {
          50: "#fff9f5",
          100: "#fff1e7",
          200: "#fce6d5",
          300: "#f7d6bd",
          400: "#f0b58b",
          500: "#e86c13",
          600: "#d45a08",
          700: "#bd3e0c",
          800: "#9e3513",
          900: "#6b2711",
        },
        yellow: {
          50: "#fffcef",
          100: "#fff7d3",
          200: "#f7e9a8",
          300: "#f5e171",
          400: "#f2d14b",
          500: "#edba13",
          600: "#d1930d",
          700: "#ab6e05",
          800: "#8c5600",
          900: "#733f12",
        },
        green: {
          50: "#f3fcf5",
          100: "#e4f5e9",
          200: "#daf0e1",
          300: "#cae5d4",
          400: "#b6dec5",
          500: "#59ba8b",
          600: "#30a66d",
          700: "#278f5e",
          800: "#16794c",
          900: "#173b2c",
        },
        teal: {
          50: "#f0fdfa",
          100: "#e6f7f4",
          200: "#bae8e1",
          300: "#97ded4",
          400: "#73d1c4",
          500: "#36baad",
          600: "#0b9e92",
          700: "#0f736b",
          800: "#115c57",
          900: "#114541",
        },
        blue: {
          50: "#f7fbfd",
          100: "#edf6fd",
          200: "#e3f1fd",
          300: "#c9e7fc",
          400: "#70b6f0",
          500: "#33a1ff",
          600: "#007be0",
          700: "#0070cc",
          800: "#005ca3",
          900: "#004880",
        },
        indigo: {
          100: "#ebf4ff",
          200: "#c3dafe",
          300: "#a3bffa",
          400: "#7f9cf5",
          500: "#667eea",
          600: "#5a67d8",
          700: "#4c51bf",
          800: "#434190",
          900: "#3c366b",
        },
        purple: {
          50: "#fdfaff",
          100: "#f9f0ff",
          200: "#f1e5fa",
          300: "#e9d6f5",
          400: "#d6c1e6",
          500: "#9c45e3",
          600: "#8642c2",
          700: "#6e399d",
          800: "#5c2f83",
          900: "#401863",
        },
        pink: {
          50: "#fff7fc",
          100: "#feeef8",
          200: "#f8e2f0",
          300: "#f2d4e6",
          400: "#e9c4da",
          500: "#df9eb8",
          600: "#cf3a96",
          700: "#9c2671",
          800: "#801458",
          900: "#570f3e",
        },
        violet: {
          50: "#fbfaff",
          100: "#f5f2ff",
          200: "#e5e1fa",
          300: "#dad2f7",
          400: "#bdb1f0",
          500: "#6846e3",
          600: "#5f46c7",
          700: "#4f3da1",
          800: "#392980",
          900: "#251959",
        },
        cyan: {
          50: "#f5fbfc",
          100: "#e0f8ff",
          200: "#b3ecfc",
          300: "#94e6ff",
          400: "#6bd3f2",
          500: "#34bae3",
          600: "#32a4c7",
          700: "#267a94",
          800: "#125c73",
          900: "#164759",
        },
        amber: {
          50: "#fdfaed",
          100: "#fcf3cf",
          200: "#f7e28d",
          300: "#f5d261",
          400: "#f2be3a",
          500: "#e79913",
          600: "#db7706",
          700: "#b35309",
          800: "#91400d",
          900: "#763813",
        },
        canvas: "var(--color-canvas)",
        "canvas-muted": withOpacity("--color-canvas-muted"),
        sidebar: "var(--color-sidebar)",
        surface: "var(--color-surface)",
        "surface-hover": withOpacity("--color-surface-hover"),
        border: "var(--color-border)",
        "border-main": "var(--color-border-main)",
        main: "var(--color-main)",
        muted: "var(--color-muted)",
        description: "var(--color-description)",
        "sidebar-active-bg": "var(--color-sidebar-active-bg)",
        "sidebar-active-text": "var(--color-sidebar-active-text)",
        "sidebar-active-border": "var(--color-sidebar-active-border)",
        "icon-main": "var(--color-icon-main)",
        "icon-muted": "var(--color-icon-muted)",
        "icon-contrast": "var(--color-icon-contrast)",
        "chart-pink-1": "var(--color-chart-pink-1)",
        "chart-pink-2": "var(--color-chart-pink-2)",
        "chart-pink-3": "var(--color-chart-pink-3)",
        "chart-pink-4": "var(--color-chart-pink-4)",
        "chart-pink-5": "var(--color-chart-pink-5)",
        "icon-light-active": "var(--icon-light-active)",
        "icon-light-passive": "var(--icon-light-passive)",
        "icon-dark-active": "var(--icon-dark-active)",
        "icon-dark-passive": "var(--icon-dark-passive)",
        error: withOpacity("--color-error"),
        "error-hover": "var(--color-error-hover)",
        "chart-empty": "var(--color-chart-empty)",
        "chart-blue-main": "var(--chart-blue-main)",
        "chart-blue-muted": "var(--chart-blue-muted)",
        "chart-pink-main": "var(--chart-pink-main)",
        "chart-pink-muted": "var(--chart-pink-muted)",
        "indicator-gray-bg": "var(--color-indicator-gray-bg)",
        "indicator-gray-text": "var(--color-indicator-gray-text)",
        "indicator-orange-bg": "var(--color-indicator-orange-bg)",
        "indicator-orange-text": "var(--color-indicator-orange-text)",
        "indicator-green-bg": "var(--color-indicator-green-bg)",
        "indicator-green-text": "var(--color-indicator-green-text)",
        "indicator-red-bg": "var(--color-indicator-red-bg)",
        "indicator-red-text": "var(--color-indicator-red-text)",
        "indicator-yellow-bg": "var(--color-indicator-yellow-bg)",
        "indicator-yellow-text": "var(--color-indicator-yellow-text)",
        "indicator-blue-bg": withOpacity("--color-indicator-blue-bg"),
        "indicator-blue-text": withOpacity("--color-indicator-blue-text"),
        "indicator-indigo-bg": "var(--color-indicator-indigo-bg)",
        "indicator-indigo-text": "var(--color-indicator-indigo-text)",
        "indicator-pink-bg": "var(--color-indicator-pink-bg)",
        "indicator-pink-text": "var(--color-indicator-pink-text)",
        "indicator-purple-bg": "var(--color-indicator-purple-bg)",
        "indicator-purple-text": "var(--color-indicator-purple-text)",
        "indicator-teal-bg": "var(--color-indicator-teal-bg)",
        "indicator-teal-text": "var(--color-indicator-teal-text)",
        "button-primary-bg": "var(--color-button-primary-bg)",
        "button-primary-text": "var(--color-button-primary-text)",
        "button-secondary-bg": "var(--color-button-secondary-bg)",
        "button-secondary-text": "var(--color-button-secondary-text)",
        "syntax-type": "var(--color-syntax-type)",
        "syntax-angle": "var(--color-syntax-angle)",
        "syntax-attr-name": "var(--color-syntax-attr-name)",
        "syntax-attr-value": "var(--color-syntax-attr-value)",
        "syntax-comment": "var(--color-syntax-comment)",
        "syntax-keyword": "var(--color-syntax-keyword)",
        "syntax-variable": "var(--color-syntax-variable)",
        "syntax-string": "var(--color-syntax-string)",
        backdrop: "var(--color-backdrop)",
        "chart-gradient-top": "var(--color-chart-gradient-top)",
        "chart-gradient-mid": "var(--color-chart-gradient-mid)",
        "chart-gradient-bottom": "var(--color-chart-gradient-bottom)",
        "chart-shadow": "var(--color-chart-shadow)",
        "indicator-unpaid-bg": "var(--color-indicator-unpaid-bg)",
        "indicator-unpaid-text": "var(--color-indicator-unpaid-text)",
        "indicator-paid-bg": "var(--color-indicator-paid-bg)",
        "indicator-paid-text": "var(--color-indicator-paid-text)",
        "indicator-submitted-bg": "var(--color-indicator-submitted-bg)",
        "indicator-submitted-text": "var(--color-indicator-submitted-text)",
        "indicator-success-bg": "var(--color-indicator-success-bg)",
        "indicator-success-text": "var(--color-indicator-success-text)",
        "indicator-error-bg": "var(--color-indicator-error-bg)",
        "indicator-error-text": "var(--color-indicator-error-text)",
        "indicator-draft-bg": "var(--color-indicator-draft-bg)",
        "indicator-draft-text": "var(--color-indicator-draft-text)",
        "indicator-cancelled-bg": "var(--color-indicator-cancelled-bg)",
        "indicator-cancelled-text": "var(--color-indicator-cancelled-text)",
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
      },
      fontFamily: {
        sans: ["var(--app-font)", "Inter", "sans-serif"],
      },
      spacing: {
        "7": "1.75rem",
        "14": "3.5rem",
        "18": "4.5rem",
        "28": "7rem",
        "72": "18rem",
        "80": "20rem",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        "outline-px": "var(--shadow-outline-px)",
        default: "var(--shadow-default)",
        button: "var(--shadow-button)",
        md: "var(--shadow-md)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-out": { from: { opacity: "1" }, to: { opacity: "0" } },
        "zoom-in": {
          from: { transform: "scale(0.95)" },
          to: { transform: "scale(1)" },
        },
        "zoom-out": {
          from: { transform: "scale(1)" },
          to: { transform: "scale(0.95)" },
        },
        "slide-in-from-top": {
          from: { transform: "translateY(-0.5rem)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-from-bottom": {
          from: { transform: "translateY(0.5rem)" },
          to: { transform: "translateY(0)" },
        },
      },
      animation: {
        in: "fade-in 0.2s ease-out, zoom-in 0.2s ease-out",
        out: "fade-out 0.2s ease-in, zoom-out 0.2s ease-in",
      },
    },
  },
  plugins: [],
};

export default config;
