import { getSchemas } from 'schemas/index';
import * as fs from 'fs';
import * as path from 'path';

function mapFieldTypeToRust(fieldtype: string, required: boolean): string {
  let rustType = '';
  switch (fieldtype) {
    case 'Int':
    case 'Check':
      rustType = 'i64';
      break;
    case 'Float':
    case 'Percent':
    case 'Currency':
      rustType = 'f64';
      break;
    default:
      rustType = 'String';
      break;
  }
  return required ? rustType : `Option<${rustType}>`;
}

function toRustStructName(name: string): string {
  return name.replace(/[\s-]/g, '');
}

function generate() {
  // We pass '-' as country code and empty array for custom fields to get all standard schemas
  const schemas = getSchemas('-', []);
  let code = `// This file is auto-generated by scripts/generateRustTypes.ts
// Do not edit this file manually.

#![allow(non_snake_case)]

use serde::{Serialize, Deserialize};

pub trait SqliteTable: Serialize + for<'de> Deserialize<'de> {
    const TABLE_NAME: &'static str;
}
`;

  const keys = Object.keys(schemas).sort();

  const RUST_KEYWORDS = new Set([
    'as',
    'break',
    'const',
    'continue',
    'crate',
    'else',
    'enum',
    'extern',
    'false',
    'fn',
    'for',
    'if',
    'impl',
    'in',
    'let',
    'loop',
    'match',
    'mod',
    'move',
    'mut',
    'pub',
    'ref',
    'return',
    'self',
    'Self',
    'static',
    'struct',
    'super',
    'trait',
    'true',
    'type',
    'unsafe',
    'use',
    'where',
    'while',
    'async',
    'await',
    'dyn',
    'abstract',
    'become',
    'box',
    'do',
    'final',
    'macro',
    'override',
    'priv',
    'typeof',
    'unsized',
    'virtual',
    'yield',
    'try',
    'union',
  ]);

  for (const key of keys) {
    const schema = schemas[key];
    if (!schema) continue;

    const structName = toRustStructName(schema.name);

    code += `\n#[derive(Debug, Clone, Serialize, Deserialize)]\n`;
    code += `#[serde(rename_all = "camelCase")]\n`;
    code += `pub struct ${structName} {\n`;

    const seen = new Set<string>();

    for (const field of schema.fields) {
      if (!field.fieldname || field.fieldname.trim() === '') continue;
      if (seen.has(field.fieldname)) continue;
      seen.add(field.fieldname);

      let rustName = field.fieldname;
      if (RUST_KEYWORDS.has(rustName)) {
        rustName = `r#${rustName}`;
      }

      if (field.fieldtype === 'Table') {
        const targetType = toRustStructName(
          field.target || 'serde_json::Value'
        );
        code += `    #[serde(default)]\n`;
        code += `    pub ${rustName}: Vec<${targetType}>,\n`;
      } else {
        const isRequired = field.required || field.fieldname === 'name';
        const rType = mapFieldTypeToRust(field.fieldtype, isRequired);
        code += `    pub ${rustName}: ${rType},\n`;
      }
    }
    code += `}\n\n`;

    if (!schema.isSingle) {
      code += `impl SqliteTable for ${structName} {\n`;
      code += `    const TABLE_NAME: &'static str = "${schema.name}";\n`;
      code += `}\n`;
    }
  }

  const outputPath = path.join(__dirname, '../src-tauri/src/models.rs');
  fs.writeFileSync(outputPath, code, 'utf-8');
  console.log(`Successfully generated Rust types to ${outputPath}`);
}

generate();
