// This file is auto-generated by scripts/generateRustTypes.ts
// Do not edit this file manually.

#![allow(non_snake_case)]

use serde::{Serialize, Deserialize};

pub trait SqliteTable: Serialize + for<'de> Deserialize<'de> {
    const TABLE_NAME: &'static str;
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Account {
    pub name: String,
    pub rootType: String,
    pub parentAccount: Option<String>,
    pub accountType: Option<String>,
    pub isGroup: Option<i64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub lft: i64,
    pub rgt: i64,
}

impl SqliteTable for Account {
    const TABLE_NAME: &'static str = "Account";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccountingLedgerEntry {
    pub name: String,
    pub date: Option<String>,
    pub party: Option<String>,
    pub account: String,
    pub debit: Option<f64>,
    pub credit: Option<f64>,
    pub referenceType: Option<String>,
    pub referenceName: Option<String>,
    pub reverted: Option<i64>,
    pub reverts: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for AccountingLedgerEntry {
    const TABLE_NAME: &'static str = "AccountingLedgerEntry";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AccountingSettings {
    pub fullname: String,
    pub companyName: String,
    pub bankName: String,
    pub country: String,
    pub email: String,
    pub writeOffAccount: Option<String>,
    pub roundOffAccount: Option<String>,
    pub discountAccount: Option<String>,
    pub enableDiscounting: Option<i64>,
    pub enableInventory: Option<i64>,
    pub enablePriceList: Option<i64>,
    pub enableInvoiceReturns: Option<i64>,
    pub enableFormCustomization: Option<i64>,
    pub enableERPNextSync: Option<i64>,
    pub enableLead: Option<i64>,
    pub enablePricingRule: Option<i64>,
    pub enableItemEnquiry: Option<i64>,
    pub enableLoyaltyProgram: Option<i64>,
    pub enableCouponCode: Option<i64>,
    pub enableitemGroup: Option<i64>,
    pub enablePointOfSaleWithOutInventory: Option<i64>,
    pub enablePartialPayment: Option<i64>,
    pub fiscalYearStart: String,
    pub fiscalYearEnd: String,
    pub setupComplete: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Address {
    pub name: String,
    pub addressLine1: String,
    pub addressLine2: Option<String>,
    pub city: String,
    pub country: String,
    pub state: Option<String>,
    pub postalCode: Option<String>,
    pub emailAddress: Option<String>,
    pub phone: Option<String>,
    pub fax: Option<String>,
    pub addressDisplay: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Address {
    const TABLE_NAME: &'static str = "Address";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppliedCouponCodes {
    pub name: String,
    pub coupons: Option<String>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for AppliedCouponCodes {
    const TABLE_NAME: &'static str = "AppliedCouponCodes";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Batch {
    pub name: String,
    pub item: Option<String>,
    pub expiryDate: Option<String>,
    pub manufactureDate: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Batch {
    const TABLE_NAME: &'static str = "Batch";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchSeries {
    pub name: String,
    pub start: i64,
    pub padZeros: i64,
    pub current: i64,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for BatchSeries {
    const TABLE_NAME: &'static str = "BatchSeries";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClosingAmounts {
    pub name: String,
    pub paymentMethod: String,
    pub openingAmount: Option<f64>,
    pub closingAmount: Option<f64>,
    pub expectedAmount: Option<f64>,
    pub differenceAmount: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for ClosingAmounts {
    const TABLE_NAME: &'static str = "ClosingAmounts";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClosingCash {
    pub name: String,
    pub denomination: f64,
    pub count: i64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for ClosingCash {
    const TABLE_NAME: &'static str = "ClosingCash";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CollectionRulesItems {
    pub name: String,
    pub tierName: Option<String>,
    pub collectionFactor: Option<f64>,
    pub minimumTotalSpent: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for CollectionRulesItems {
    const TABLE_NAME: &'static str = "CollectionRulesItems";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Color {
    pub name: String,
    pub hexvalue: String,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Color {
    const TABLE_NAME: &'static str = "Color";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CouponCode {
    pub name: String,
    pub couponName: String,
    pub isEnabled: i64,
    pub pricingRule: String,
    pub minAmount: Option<f64>,
    pub maxAmount: Option<f64>,
    pub validFrom: String,
    pub validTo: String,
    pub maximumUse: i64,
    pub used: i64,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for CouponCode {
    const TABLE_NAME: &'static str = "CouponCode";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Currency {
    pub name: String,
    pub fraction: Option<String>,
    pub fractionUnits: Option<i64>,
    pub smallestValue: Option<f64>,
    pub symbol: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Currency {
    const TABLE_NAME: &'static str = "Currency";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomField {
    pub name: String,
    pub label: String,
    pub fieldname: String,
    pub fieldtype: String,
    pub isRequired: Option<i64>,
    pub default: Option<String>,
    pub section: Option<String>,
    pub tab: Option<String>,
    pub options: Option<String>,
    pub target: Option<String>,
    pub references: Option<String>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for CustomField {
    const TABLE_NAME: &'static str = "CustomField";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomForm {
    pub name: String,
    #[serde(default)]
    pub customFields: Vec<CustomField>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for CustomForm {
    const TABLE_NAME: &'static str = "CustomForm";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DefaultCashDenominations {
    pub name: String,
    pub denomination: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for DefaultCashDenominations {
    const TABLE_NAME: &'static str = "DefaultCashDenominations";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Defaults {
    pub salesPaymentAccount: Option<String>,
    pub purchasePaymentAccount: Option<String>,
    pub shipmentLocation: Option<String>,
    pub purchaseReceiptLocation: Option<String>,
    pub salesInvoiceNumberSeries: Option<String>,
    pub purchaseInvoiceNumberSeries: Option<String>,
    pub journalEntryNumberSeries: Option<String>,
    pub paymentNumberSeries: Option<String>,
    pub stockMovementNumberSeries: Option<String>,
    pub shipmentNumberSeries: Option<String>,
    pub purchaseReceiptNumberSeries: Option<String>,
    pub salesQuoteNumberSeries: Option<String>,
    pub salesInvoiceTerms: Option<String>,
    pub purchaseInvoiceTerms: Option<String>,
    pub shipmentTerms: Option<String>,
    pub purchaseReceiptTerms: Option<String>,
    pub salesQuotePrintTemplate: Option<String>,
    pub salesInvoicePrintTemplate: Option<String>,
    pub purchaseInvoicePrintTemplate: Option<String>,
    pub journalEntryPrintTemplate: Option<String>,
    pub paymentPrintTemplate: Option<String>,
    pub shipmentPrintTemplate: Option<String>,
    pub purchaseReceiptPrintTemplate: Option<String>,
    pub stockMovementPrintTemplate: Option<String>,
    pub posPrintTemplate: Option<String>,
    pub posCustomer: Option<String>,
    #[serde(default)]
    pub posCashDenominations: Vec<DefaultCashDenominations>,
    pub saveButtonColour: Option<String>,
    pub cancelButtonColour: Option<String>,
    pub submitButtonColour: Option<String>,
    pub heldButtonColour: Option<String>,
    pub returnButtonColour: Option<String>,
    pub payButtonColour: Option<String>,
    pub payAndPrintButtonColour: Option<String>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ERPNextSyncQueue {
    pub name: String,
    pub referenceType: String,
    pub documentName: String,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for ERPNextSyncQueue {
    const TABLE_NAME: &'static str = "ERPNextSyncQueue";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ERPNextSyncSettings {
    pub deviceID: Option<String>,
    pub baseURL: Option<String>,
    pub authToken: Option<String>,
    pub initialSyncData: Option<i64>,
    pub integrationAppVersion: Option<String>,
    pub isEnabled: Option<i64>,
    pub dataSyncInterval: Option<String>,
    pub syncDataFromServer: Option<String>,
    pub syncDataToServer: Option<String>,
    pub registerInstance: Option<String>,
    pub syncSettings: Option<String>,
    pub syncDataToERPNext: Option<String>,
    pub fetchFromERPNextQueue: Option<String>,
    pub clearSyncedDocsFromErpNextSyncQueue: Option<String>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FetchFromERPNextQueue {
    pub name: String,
    pub referenceType: String,
    pub documentName: String,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for FetchFromERPNextQueue {
    const TABLE_NAME: &'static str = "FetchFromERPNextQueue";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetStarted {
    pub onboardingComplete: Option<i64>,
    pub companySetup: Option<i64>,
    pub systemSetup: Option<i64>,
    pub printSetup: Option<i64>,
    pub salesItemCreated: Option<i64>,
    pub purchaseItemCreated: Option<i64>,
    pub customerCreated: Option<i64>,
    pub supplierCreated: Option<i64>,
    pub invoiceCreated: Option<i64>,
    pub billCreated: Option<i64>,
    pub chartOfAccountsReviewed: Option<i64>,
    pub openingBalanceChecked: Option<i64>,
    pub taxesAdded: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IntegrationErrorLog {
    pub name: String,
    pub spacer: Option<String>,
    pub data: Option<String>,
    pub error: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for IntegrationErrorLog {
    const TABLE_NAME: &'static str = "IntegrationErrorLog";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InventorySettings {
    pub defaultLocation: Option<String>,
    pub stockInHand: Option<String>,
    pub stockReceivedButNotBilled: Option<String>,
    pub costOfGoodsSold: Option<String>,
    pub enableBarcodes: Option<i64>,
    pub enableBatches: Option<i64>,
    pub enableSerialNumber: Option<i64>,
    pub enableUomConversions: Option<i64>,
    pub enablePointOfSale: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Item {
    pub image: Option<String>,
    pub name: String,
    pub itemCode: Option<String>,
    pub itemGroup: Option<String>,
    pub r#for: String,
    pub itemType: Option<String>,
    pub unit: Option<String>,
    pub rate: Option<f64>,
    pub description: Option<String>,
    pub incomeAccount: String,
    pub expenseAccount: String,
    pub tax: Option<String>,
    pub hsnCode: Option<String>,
    pub barcode: Option<String>,
    pub trackItem: Option<i64>,
    pub hasBatch: Option<i64>,
    pub batchSeries: Option<String>,
    pub hasSerialNumber: Option<i64>,
    pub serialNumberSeries: Option<String>,
    #[serde(default)]
    pub uomConversions: Vec<UOMConversionItem>,
    pub datafromErp: Option<i64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Item {
    const TABLE_NAME: &'static str = "Item";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemEnquiry {
    pub name: String,
    pub item: String,
    pub customer: Option<String>,
    pub contact: Option<String>,
    pub description: Option<String>,
    pub similarProduct: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for ItemEnquiry {
    const TABLE_NAME: &'static str = "ItemEnquiry";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemGroup {
    pub image: Option<String>,
    pub name: String,
    pub tax: Option<String>,
    pub hsnCode: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for ItemGroup {
    const TABLE_NAME: &'static str = "ItemGroup";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JournalEntry {
    pub name: String,
    pub numberSeries: String,
    pub entryType: String,
    pub date: String,
    #[serde(default)]
    pub accounts: Vec<JournalEntryAccount>,
    pub referenceNumber: Option<String>,
    pub referenceDate: Option<String>,
    pub userRemark: Option<String>,
    pub attachment: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for JournalEntry {
    const TABLE_NAME: &'static str = "JournalEntry";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JournalEntryAccount {
    pub name: String,
    pub account: String,
    pub debit: Option<f64>,
    pub credit: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for JournalEntryAccount {
    const TABLE_NAME: &'static str = "JournalEntryAccount";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Lead {
    pub name: String,
    pub status: String,
    pub email: Option<String>,
    pub mobile: Option<String>,
    pub address: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Lead {
    const TABLE_NAME: &'static str = "Lead";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Location {
    pub name: String,
    pub address: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Location {
    const TABLE_NAME: &'static str = "Location";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyPointEntry {
    pub name: String,
    pub loyaltyProgram: String,
    pub loyaltyProgramTier: Option<String>,
    pub customer: String,
    pub invoice: String,
    pub loyaltyPoints: Option<i64>,
    pub purchaseAmount: f64,
    pub expiryDate: Option<String>,
    pub postingDate: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for LoyaltyPointEntry {
    const TABLE_NAME: &'static str = "LoyaltyPointEntry";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoyaltyProgram {
    pub name: String,
    pub fromDate: String,
    pub toDate: String,
    pub isEnabled: i64,
    #[serde(default)]
    pub collectionRules: Vec<CollectionRulesItems>,
    pub conversionFactor: f64,
    pub expiryDuration: Option<i64>,
    pub expenseAccount: String,
    pub maximumUse: Option<i64>,
    pub used: Option<i64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for LoyaltyProgram {
    const TABLE_NAME: &'static str = "LoyaltyProgram";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Misc {
    pub openCount: Option<i64>,
    pub useFullWidth: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NumberSeries {
    pub name: String,
    pub start: i64,
    pub padZeros: i64,
    pub referenceType: String,
    pub current: i64,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for NumberSeries {
    const TABLE_NAME: &'static str = "NumberSeries";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpeningAmounts {
    pub name: String,
    pub paymentMethod: String,
    pub amount: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for OpeningAmounts {
    const TABLE_NAME: &'static str = "OpeningAmounts";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpeningCash {
    pub name: String,
    pub denomination: f64,
    pub count: i64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for OpeningCash {
    const TABLE_NAME: &'static str = "OpeningCash";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct POSClosingShift {
    pub name: String,
    pub closingDate: Option<String>,
    #[serde(default)]
    pub closingCash: Vec<ClosingCash>,
    #[serde(default)]
    pub closingAmounts: Vec<ClosingAmounts>,
    pub openingShift: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for POSClosingShift {
    const TABLE_NAME: &'static str = "POSClosingShift";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct POSOpeningShift {
    pub name: String,
    pub openingDate: Option<String>,
    #[serde(default)]
    pub openingCash: Vec<OpeningCash>,
    #[serde(default)]
    pub openingAmounts: Vec<OpeningAmounts>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for POSOpeningShift {
    const TABLE_NAME: &'static str = "POSOpeningShift";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct POSProfile {
    pub name: String,
    pub posCustomer: Option<String>,
    pub inventory: String,
    pub posPrintTemplate: Option<String>,
    pub posUI: String,
    pub isShiftOpen: Option<i64>,
    pub itemVisibility: String,
    pub canChangeRate: Option<i64>,
    pub hideUnavailableItems: Option<i64>,
    pub canEditDiscount: Option<i64>,
    pub ignorePricingRule: Option<i64>,
    pub saveButtonColour: Option<String>,
    pub cancelButtonColour: Option<String>,
    pub submitButtonColour: Option<String>,
    pub heldButtonColour: Option<String>,
    pub returnButtonColour: Option<String>,
    pub payButtonColour: Option<String>,
    pub payAndPrintButtonColour: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for POSProfile {
    const TABLE_NAME: &'static str = "POSProfile";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct POSSettings {
    pub inventory: Option<String>,
    pub posProfile: Option<String>,
    pub cashAccount: String,
    pub writeOffAccount: Option<String>,
    pub posUI: String,
    pub isShiftOpen: Option<i64>,
    pub defaultAccount: String,
    pub weightEnabledBarcode: Option<i64>,
    pub checkDigits: Option<i64>,
    pub itemCodeDigits: Option<i64>,
    pub itemVisibility: Option<String>,
    pub itemVisibilityERP: Option<String>,
    pub canChangeRate: Option<i64>,
    pub hideUnavailableItems: Option<i64>,
    pub canEditDiscount: Option<i64>,
    pub ignorePricingRule: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Party {
    pub image: Option<String>,
    pub name: String,
    pub role: String,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub defaultAccount: Option<String>,
    pub currency: Option<String>,
    pub fromLead: Option<String>,
    pub loyaltyProgram: Option<String>,
    pub loyaltyPoints: Option<i64>,
    pub taxId: Option<String>,
    pub outstandingAmount: Option<f64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Party {
    const TABLE_NAME: &'static str = "Party";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PatchRun {
    pub name: String,
    pub failed: Option<i64>,
    pub version: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for PatchRun {
    const TABLE_NAME: &'static str = "PatchRun";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Payment {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub date: String,
    pub paymentType: String,
    pub account: String,
    pub paymentAccount: String,
    pub paymentMethod: String,
    pub clearanceDate: Option<String>,
    pub referenceId: Option<String>,
    pub referenceDate: Option<String>,
    pub amount: f64,
    pub writeoff: Option<f64>,
    pub amountPaid: Option<f64>,
    #[serde(default)]
    pub taxes: Vec<TaxSummary>,
    #[serde(default)]
    pub r#for: Vec<PaymentFor>,
    pub attachment: Option<String>,
    pub referenceType: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for Payment {
    const TABLE_NAME: &'static str = "Payment";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentFor {
    pub name: String,
    pub referenceType: String,
    pub referenceName: String,
    pub amount: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PaymentFor {
    const TABLE_NAME: &'static str = "PaymentFor";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaymentMethod {
    pub name: String,
    pub r#type: String,
    pub account: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for PaymentMethod {
    const TABLE_NAME: &'static str = "PaymentMethod";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PriceList {
    pub name: String,
    pub isEnabled: Option<i64>,
    pub isSales: Option<i64>,
    pub isPurchase: Option<i64>,
    #[serde(default)]
    pub priceListItem: Vec<PriceListItem>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for PriceList {
    const TABLE_NAME: &'static str = "PriceList";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PriceListItem {
    pub name: String,
    pub item: String,
    pub unit: Option<String>,
    pub rate: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PriceListItem {
    const TABLE_NAME: &'static str = "PriceListItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PricingRule {
    pub name: String,
    pub numberSeries: String,
    pub isEnabled: Option<i64>,
    pub title: String,
    #[serde(default)]
    pub appliedItems: Vec<PricingRuleItem>,
    pub discountType: String,
    pub isCouponCodeBased: Option<i64>,
    pub priority: String,
    pub priceDiscountType: Option<String>,
    pub discountRate: Option<f64>,
    pub discountPercentage: Option<f64>,
    pub discountAmount: Option<f64>,
    pub freeItem: Option<String>,
    pub freeItemQuantity: Option<f64>,
    pub freeItemUnit: Option<String>,
    pub roundFreeItemQty: Option<i64>,
    pub roundingMethod: String,
    pub isRecursive: Option<i64>,
    pub recurseEvery: Option<f64>,
    pub minQuantity: Option<f64>,
    pub maxQuantity: Option<f64>,
    pub minAmount: Option<f64>,
    pub maxAmount: Option<f64>,
    pub validFrom: Option<String>,
    pub validTo: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for PricingRule {
    const TABLE_NAME: &'static str = "PricingRule";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PricingRuleDetail {
    pub name: String,
    pub referenceName: Option<String>,
    pub referenceItem: Option<String>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PricingRuleDetail {
    const TABLE_NAME: &'static str = "PricingRuleDetail";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PricingRuleItem {
    pub name: String,
    pub item: String,
    pub unit: Option<String>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PricingRuleItem {
    const TABLE_NAME: &'static str = "PricingRuleItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PrintSettings {
    pub logo: Option<String>,
    pub companyName: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub color: Option<String>,
    pub font: Option<String>,
    pub displayLogo: Option<i64>,
    pub amountInWords: Option<i64>,
    pub displayTime: Option<i64>,
    pub displayDescription: Option<i64>,
    pub displaytermsandconditions: Option<i64>,
    pub posPrintWidth: Option<f64>,
    pub termsAndConditions: Option<String>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PrintTemplate {
    pub name: String,
    pub r#type: String,
    pub template: String,
    pub height: Option<f64>,
    pub width: Option<f64>,
    pub isCustom: Option<i64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for PrintTemplate {
    const TABLE_NAME: &'static str = "PrintTemplate";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoice {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub account: String,
    pub date: String,
    pub priceList: Option<String>,
    #[serde(default)]
    pub items: Vec<PurchaseInvoiceItem>,
    pub netTotal: Option<f64>,
    #[serde(default)]
    pub taxes: Vec<TaxSummary>,
    pub baseGrandTotal: Option<f64>,
    pub grandTotal: Option<f64>,
    pub setDiscountAmount: Option<i64>,
    pub discountAmount: Option<f64>,
    pub discountPercent: Option<f64>,
    pub entryCurrency: Option<String>,
    pub currency: Option<String>,
    pub exchangeRate: Option<f64>,
    pub discountAfterTax: Option<i64>,
    pub makeAutoPayment: Option<i64>,
    pub makeAutoStockTransfer: Option<i64>,
    pub outstandingAmount: Option<f64>,
    pub stockNotTransferred: Option<f64>,
    pub terms: Option<String>,
    pub attachment: Option<String>,
    pub isReturned: Option<i64>,
    pub isFullyReturned: Option<i64>,
    pub isSyncedWithErp: Option<i64>,
    pub backReference: Option<String>,
    pub returnAgainst: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for PurchaseInvoice {
    const TABLE_NAME: &'static str = "PurchaseInvoice";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceItem {
    pub name: String,
    pub item: String,
    pub itemCode: Option<String>,
    pub description: Option<String>,
    pub rate: f64,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub qty: Option<f64>,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub account: String,
    pub tax: Option<String>,
    pub amount: Option<f64>,
    pub setItemDiscountAmount: Option<i64>,
    pub itemDiscountAmount: Option<f64>,
    pub itemDiscountPercent: Option<f64>,
    pub itemDiscountedTotal: Option<f64>,
    pub itemTaxedTotal: Option<f64>,
    pub hsnCode: Option<i64>,
    pub stockNotTransferred: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PurchaseInvoiceItem {
    const TABLE_NAME: &'static str = "PurchaseInvoiceItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PurchaseReceipt {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub date: String,
    #[serde(default)]
    pub items: Vec<PurchaseReceiptItem>,
    pub grandTotal: Option<f64>,
    pub terms: Option<String>,
    pub attachment: Option<String>,
    pub isReturned: Option<i64>,
    pub backReference: Option<String>,
    pub returnAgainst: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for PurchaseReceipt {
    const TABLE_NAME: &'static str = "PurchaseReceipt";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PurchaseReceiptItem {
    pub name: String,
    pub item: String,
    pub location: String,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub serialNumber: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub rate: f64,
    pub amount: Option<f64>,
    pub itemDiscountAmount: Option<f64>,
    pub itemDiscountPercent: Option<f64>,
    pub description: Option<String>,
    pub hsnCode: Option<i64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for PurchaseReceiptItem {
    const TABLE_NAME: &'static str = "PurchaseReceiptItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoice {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub account: String,
    pub date: String,
    pub priceList: Option<String>,
    #[serde(default)]
    pub items: Vec<SalesInvoiceItem>,
    pub netTotal: Option<f64>,
    #[serde(default)]
    pub taxes: Vec<TaxSummary>,
    pub baseGrandTotal: Option<f64>,
    pub grandTotal: Option<f64>,
    pub setDiscountAmount: Option<i64>,
    pub discountAmount: Option<f64>,
    pub discountPercent: Option<f64>,
    pub entryCurrency: Option<String>,
    pub currency: Option<String>,
    pub exchangeRate: Option<f64>,
    pub discountAfterTax: Option<i64>,
    pub makeAutoPayment: Option<i64>,
    pub makeAutoStockTransfer: Option<i64>,
    pub outstandingAmount: Option<f64>,
    pub stockNotTransferred: Option<f64>,
    pub terms: Option<String>,
    pub attachment: Option<String>,
    pub isReturned: Option<i64>,
    pub isFullyReturned: Option<i64>,
    pub isSyncedWithErp: Option<i64>,
    pub backReference: Option<String>,
    pub returnAgainst: Option<String>,
    #[serde(default)]
    pub coupons: Vec<AppliedCouponCodes>,
    pub quote: Option<String>,
    pub loyaltyProgram: Option<String>,
    pub availableLoyaltyPoints: Option<i64>,
    pub redeemLoyaltyPoints: Option<i64>,
    pub loyaltyPoints: Option<i64>,
    pub isPOS: Option<i64>,
    pub isPricingRuleApplied: Option<i64>,
    #[serde(default)]
    pub pricingRuleDetail: Vec<PricingRuleDetail>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for SalesInvoice {
    const TABLE_NAME: &'static str = "SalesInvoice";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceItem {
    pub name: String,
    pub item: String,
    pub itemCode: Option<String>,
    pub description: Option<String>,
    pub rate: f64,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub qty: Option<f64>,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub account: String,
    pub tax: Option<String>,
    pub amount: Option<f64>,
    pub setItemDiscountAmount: Option<i64>,
    pub itemDiscountAmount: Option<f64>,
    pub itemDiscountPercent: Option<f64>,
    pub itemDiscountedTotal: Option<f64>,
    pub itemTaxedTotal: Option<f64>,
    pub hsnCode: Option<i64>,
    pub stockNotTransferred: Option<f64>,
    pub isFreeItem: Option<i64>,
    pub pricingRule: Option<String>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for SalesInvoiceItem {
    const TABLE_NAME: &'static str = "SalesInvoiceItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SalesQuote {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub date: String,
    pub priceList: Option<String>,
    #[serde(default)]
    pub items: Vec<SalesQuoteItem>,
    pub netTotal: Option<f64>,
    #[serde(default)]
    pub taxes: Vec<TaxSummary>,
    pub baseGrandTotal: Option<f64>,
    pub grandTotal: Option<f64>,
    pub setDiscountAmount: Option<i64>,
    pub discountAmount: Option<f64>,
    pub discountPercent: Option<f64>,
    pub entryCurrency: Option<String>,
    pub currency: Option<String>,
    pub exchangeRate: Option<f64>,
    pub discountAfterTax: Option<i64>,
    pub makeAutoPayment: Option<i64>,
    pub outstandingAmount: Option<f64>,
    pub terms: Option<String>,
    pub attachment: Option<String>,
    pub isFullyReturned: Option<i64>,
    pub isSyncedWithErp: Option<i64>,
    pub referenceType: String,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for SalesQuote {
    const TABLE_NAME: &'static str = "SalesQuote";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SalesQuoteItem {
    pub name: String,
    pub item: String,
    pub itemCode: Option<String>,
    pub description: Option<String>,
    pub rate: f64,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub qty: Option<f64>,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub account: String,
    pub tax: Option<String>,
    pub amount: Option<f64>,
    pub setItemDiscountAmount: Option<i64>,
    pub itemDiscountAmount: Option<f64>,
    pub itemDiscountPercent: Option<f64>,
    pub itemDiscountedTotal: Option<f64>,
    pub itemTaxedTotal: Option<f64>,
    pub hsnCode: Option<i64>,
    pub stockNotTransferred: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for SalesQuoteItem {
    const TABLE_NAME: &'static str = "SalesQuoteItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SerialNumber {
    pub name: String,
    pub item: String,
    pub description: Option<String>,
    pub status: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for SerialNumber {
    const TABLE_NAME: &'static str = "SerialNumber";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SerialNumberSeries {
    pub name: String,
    pub start: i64,
    pub padZeros: i64,
    pub current: i64,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for SerialNumberSeries {
    const TABLE_NAME: &'static str = "SerialNumberSeries";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetupWizard {
    pub logo: Option<String>,
    pub companyName: String,
    pub fullname: String,
    pub email: String,
    pub country: String,
    pub currency: String,
    pub bankName: String,
    pub chartOfAccounts: String,
    pub fiscalYearStart: String,
    pub fiscalYearEnd: String,
    pub completed: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Shipment {
    pub name: String,
    pub numberSeries: String,
    pub party: String,
    pub date: String,
    #[serde(default)]
    pub items: Vec<ShipmentItem>,
    pub grandTotal: Option<f64>,
    pub terms: Option<String>,
    pub attachment: Option<String>,
    pub isReturned: Option<i64>,
    pub backReference: Option<String>,
    pub returnAgainst: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for Shipment {
    const TABLE_NAME: &'static str = "Shipment";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ShipmentItem {
    pub name: String,
    pub item: String,
    pub location: String,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub serialNumber: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub rate: f64,
    pub amount: Option<f64>,
    pub itemDiscountAmount: Option<f64>,
    pub itemDiscountPercent: Option<f64>,
    pub description: Option<String>,
    pub hsnCode: Option<i64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for ShipmentItem {
    const TABLE_NAME: &'static str = "ShipmentItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SingleValue {
    pub name: String,
    pub parent: String,
    pub fieldname: String,
    pub value: String,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for SingleValue {
    const TABLE_NAME: &'static str = "SingleValue";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StockLedgerEntry {
    pub name: String,
    pub date: Option<String>,
    pub location: Option<String>,
    pub batch: Option<String>,
    pub serialNumber: Option<String>,
    pub item: Option<String>,
    pub rate: Option<f64>,
    pub quantity: Option<f64>,
    pub referenceType: Option<String>,
    pub referenceName: Option<String>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for StockLedgerEntry {
    const TABLE_NAME: &'static str = "StockLedgerEntry";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StockMovement {
    pub name: String,
    pub numberSeries: String,
    pub movementType: String,
    pub date: String,
    #[serde(default)]
    pub items: Vec<StockMovementItem>,
    pub amount: Option<f64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
    pub submitted: i64,
    pub cancelled: i64,
}

impl SqliteTable for StockMovement {
    const TABLE_NAME: &'static str = "StockMovement";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StockMovementItem {
    pub name: String,
    pub item: String,
    pub fromLocation: Option<String>,
    pub toLocation: Option<String>,
    pub transferUnit: Option<String>,
    pub transferQuantity: f64,
    pub unit: Option<String>,
    pub batch: Option<String>,
    pub serialNumber: Option<String>,
    pub quantity: f64,
    pub unitConversionFactor: f64,
    pub rate: f64,
    pub amount: Option<f64>,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for StockMovementItem {
    const TABLE_NAME: &'static str = "StockMovementItem";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SystemSettings {
    pub dateFormat: String,
    pub hideGetStarted: Option<i64>,
    pub version: Option<String>,
    pub allowFilterBypass: Option<i64>,
    pub removeFilter: Option<i64>,
    pub locale: String,
    pub displayPrecision: i64,
    pub currency: String,
    pub internalPrecision: Option<i64>,
    pub countryCode: Option<String>,
    pub instanceId: Option<String>,
    pub darkMode: Option<i64>,
    pub displayTermsAndConditions: Option<i64>,
}


#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tax {
    pub name: String,
    #[serde(default)]
    pub details: Vec<TaxDetail>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for Tax {
    const TABLE_NAME: &'static str = "Tax";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaxDetail {
    pub name: String,
    pub account: String,
    pub payment_account: Option<String>,
    pub rate: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for TaxDetail {
    const TABLE_NAME: &'static str = "TaxDetail";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TaxSummary {
    pub name: String,
    pub account: String,
    pub from_account: Option<String>,
    pub rate: f64,
    pub amount: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for TaxSummary {
    const TABLE_NAME: &'static str = "TaxSummary";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UOM {
    pub name: String,
    pub isWhole: Option<i64>,
    pub createdBy: String,
    pub modifiedBy: String,
    pub created: String,
    pub modified: String,
}

impl SqliteTable for UOM {
    const TABLE_NAME: &'static str = "UOM";
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UOMConversionItem {
    pub name: String,
    pub uom: String,
    pub conversionFactor: f64,
    pub idx: i64,
    pub parent: String,
    pub parentSchemaName: String,
    pub parentFieldname: String,
}

impl SqliteTable for UOMConversionItem {
    const TABLE_NAME: &'static str = "UOMConversionItem";
}
