name: Test

on:
  push:
    branches: [$default-branch]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  setup_and_test:
    runs-on: macos-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24.22.2'

      - name: Set pnpm version
        run: pnpm set version 10.33.2

      - name: Checkout Books
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm

      - name: Run Tests
        run: pnpm test

  setup_and_uitest:
    runs-on: macos-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24.16.0'

      - name: Set pnpm version
        run: pnpm set version 11.5.1

      - name: Checkout Auditbooks
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm

      - name: Build Source Files
        run: pnpm build --nosign --nopackage

      - name: Run UI Tests
        run: pnpm uitest
